#!/usr/bin/bash

# WARNING: THIS SCRIPT IS ONLY WORKS FOR CENTOS, RHEL, AND ROCKY LINUX DISTRO


# Date: 3/1/2022
# Developer: Mitchel R Moon, Quan N Nguyen
# Description: This is create repo tool using bash shell and git hook,
# which can create a git repo for the project, and update the code inside this repo
# and code those to apache home directory => deploying directly after pushing!!!


# getting current username
currentUser="$(whoami)"


# check parameter of the bash shell
if [ "$#" -ne "1" ]; then
	echo "Usage: createRepo REPO"$'\n'
else
	cd /home/$currentUser/Development || exit

	bareRepo=$1".git"
	repo=$1

	echo "Creating the bare repo..."

	git --bare init $bareRepo

	echo "Adding necessary hook(s)..."

	cd $bareRepo/hooks
	echo "#!/usr/bin/sh"$'\n'$'\n'"echo "\""Pulling changes into the live directory..."\"""$'\n'$'\n'"cd /var/www/html/"$repo" || exit"$'\n'"unset GIT_DIR"$'\n'"git pull"$'\n'$'\n'"exec git-update-server-info"$'\n'"echo "\""Done"\""$'\n'" > post-update
	chmod 755 post-update

	echo "Cloning the new repo..."

	cd /var/www/html

	git clone /home/qnguyen/Development/$bareRepo

	echo "Finished!!!."$'\n'
fi
